---
- name: Setting up the Security Group for new instance
  ec2_group:
      name: "{{ aws_security_group_name }}"
      description: Allowing Traffic on port 22
      profile: "{{ aws_profile_name }}"
      region: "{{ aws_region }}"
      tags:
        Name: "{{ aws_security_group_name }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          # cidr_ip: 0.0.0.0/0
          cidr_ip: 10.0.0.0/8

        - proto: icmp
          from_port: -1
          to_port: -1
          #cidr_ip: 0.0.0.0/0
          cidr_ip: 10.0.0.0/8

      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
      vpc_id:  "{{ aws_vpc_id }}"

- name: Provision EC2 instance
  ec2:
      profile: "{{ aws_profile_name }}"
      key_name: "{{ aws_keypair_name }}"
      region: "{{ aws_region }}"
      instance_type: "{{ aws_ec2_instance_type }}"
      image: "{{ aws_ec2_image }}"
      wait: yes
      wait_timeout: 500
      count: "{{ aws_ec2_instance_count }}"
      instance_tags:
        Name: "{{ aws_ec2_instance_name }}"
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      monitoring: yes
      vpc_subnet_id: "{{ aws_subnet_id }}"
      assign_public_ip: no
      group: "{{ aws_security_group_name }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
      #host: "{{ item.public_ip }}"  
      host: "{{ item.private_ip }}"  
      port: 22
      delay: 60
      timeout: 320
      state: started
  with_items: "{{ ec2.instances }}"

- name: Add all instance IPs to bamboo-agent-hosts group
  add_host: 
    #hostname: "{{ item.public_ip }}" 
    hostname: "{{ item.private_ip }}" 
    groups: bamboo-agent-hosts
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{aws_keypair_keyfile}}"
    ansible_python_interpreter: /usr/bin/python3
  loop: "{{ ec2.instances }}"   

