---
- include: ../../common/security-group.yml

- name: Provision EC2 instance
  amazon.aws.ec2:
      profile: "{{ aws_profile_name }}"
      key_name: "{{ aws_keypair_name }}"
      region: "{{ aws_region }}"
      instance_type: "{{ aws_ec2_instance_type }}"
      image: "{{ aws_ec2_image }}"
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags:
        Name: "{{ aws_ec2_instance_name }}"
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      monitoring: yes
      vpc_subnet_id: "{{ aws_subnet_id }}"
      assign_public_ip: "{{ aws_ec2_assign_public_ip }}"
      group: "{{ aws_security_group_name }}"
  register: ec2


- include: ../../common/ec2-ssh.yml
  when: ec2.instances|length > 0

