---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required software 
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-8-jdk
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64