---
- hosts: localserver
  name: creation Bamboo Agent 
  gather_facts: False
  vars: 
    aws_profile_name: SCATS
    aws_ec2_instance_name: Bamboo-Agent-Test
    aws_ec2_instance_count: 1
    aws_security_group_name: Bamboo_Agent_Security_Group
    aws_ec2_image: ami-0567f647e75c7bc05 
    aws_ec2_instance_type: t2.micro
    aws_vpc_id: vpc-0fe19049e32fbc259
    aws_region: ap-southeast-2
    aws_subnet_id: subnet-0c193ce6122d76a14
    aws_keypair_name: YongTestDevops
    aws_keypair_keyfile: /Users/yong.zeng/Project/SCATS-TfNSW/aws/YongTestDevops.pem  
  roles:
    - bamboo-agent-create
  

- hosts: bamboo-agent-hosts
  name: configuration Bamboo Agent 
  become: yes
  gather_facts: true
  roles:
    - bamboo-agent-config