---
- hosts: server
  gather_facts: false
  vars: 
    aws_ec2_instance_name: Bamboo-Agent
    aws_region: ap-southeast-2
  tasks:
    - name: Collect EC2 instance info
      community.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
            "tag:Name": "{{ aws_ec2_instance_name }}" 
      register: ec2_node_info

    - name: Terminate EC2 instance
      ec2:
         instance_ids: "{{ item.instance_id }}"
         region: "{{ aws_region }}"
         state: absent 
         wait: yes
      with_items: "{{ec2_node_info.instances}}"   
