---
- hosts: localserver
  name: creation Bamboo Agent 
  gather_facts: False
  vars_files: 
    - var.yml 
  roles:
    - bamboo-agent-terminate
    - bamboo-agent-create
  
  
- hosts: bamboo-agent-ami-hosts
  name: configuration Bamboo Agent 
  become: yes
  gather_facts: true
  vars_files: 
    - var.yml 
  roles:
    - bamboo-agent-config