---
- hosts: localserver
  name: creation Bamboo Agent 
  gather_facts: False
  vars_files: 
    - var.yml 
  tasks:
    - name: Collecting ec2 ami information
      amazon.aws.ec2_ami_info:
          profile: "{{ aws_profile_name }}"
          region: "{{ aws_region }}"
          filters:
            "tag:Name": "{{ aws_ec2_ami_tag_name }}"
      register: ec2_ami_info



     
