---
- name: Waiting for SSH to come up 
  wait_for:
      host: "{{ (aws_ec2_assign_public_ip == true) | ternary(ec2.instances[0].public_ip, ec2.instances[0].private_ip)}}"  
      port: 22
      delay: 60
      timeout: 320
      state: started
  when: (ec2.instances|length > 0) 

- name: add ip to bamboo-agent-ami-hosts 
  add_host: 
    hostname: "{{ (aws_ec2_assign_public_ip == true) | ternary(ec2.instances[0].public_ip, ec2.instances[0].private_ip)}}"  
    groups: bamboo-agent-ami-hosts
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{aws_keypair_keyfile}}"
    ansible_python_interpreter: /usr/bin/python3
  when: (ec2.instances|length > 0)






